version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
        interval: daily
  - package-ecosystem: docker
    directory: /
    schedule:
        interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
        interval: daily
  - package-ecosystem: cargo
    directory: /pzzld
    schedule:
        interval: daily
  - package-ecosystem: cargo
    directory: /xtask
    schedule:
        interval: daily
  - package-ecosystem: cargo
    directory: /wasm
    schedule:
        interval: daily
  - package-ecosystem: cargo
    directory: /crates/compilers
    schedule:
        interval: daily
  - package-ecosystem: cargo
    directory: /crates/core
    schedule:
        interval: daily
  - package-ecosystem: cargo
    directory: /crates/gateways
    schedule:
        interval: daily
  - package-ecosystem: cargo
    directory: /crates/pzzld
    schedule:
        interval: daily
  - package-ecosystem: cargo
    directory: /crates/wallets
    schedule:
        interval: daily
