version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
        interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
        interval: daily
  - package-ecosystem: cargo
    directory: /pzzld
    schedule:
        interval: daily
  - package-ecosystem: cargo
    directory: /core
    schedule:
        interval: daily
  - package-ecosystem: cargo
    directory: /wallets
    schedule:
        interval: daily
  - package-ecosystem: cargo
    directory: /bin/app
    schedule:
        interval: daily