[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://github.com/FL03)"]
categories = []
description = "Puzzled"
edition = "2021"
homepage = "https://github.com/FL03/pzzld/wiki"
keywords = []
license = "Apache-2.0"
name = "pzzld"
repository = "https://github.com/FL03/pzzld"
version = "0.1.0"

[lib]
crate-type = [ "cdylib", "rlib" ]
test = true

[build-dependencies]
substrate-wasm-builder = "5.0.0"

[dev-dependencies]
wasm-bindgen-test = "0.3"

[dependencies]
futures = "0.3.25"
gloo = { features = [ "futures" ], version = "0.8" }
js-sys = { features = [], version = "0.3.60" }
serde = { features = ["derive"], version = "1" }
serde_json = "1"
strum = { features = ["derive"], version = "0.24.1" }
wasm-bindgen = { features = [ "serde-serialize" ], version = "0.2.83"}

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]

[target.wasm32-unknown-unknown]

[target.wasm32-wasi]
