[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://github.com/FL03)"]
categories = []
description = "Puzzled"
edition = "2021"
homepage = "https://github.com/FL03/pzzld/wiki"
keywords = []
license = "Apache-2.0"
name = "pzzld"
readme = "README.md"
repository = "https://github.com/FL03/pzzld"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]
test = true

[build-dependencies]

[dev-dependencies]

[dependencies]
tokio = { features = [], version = "1.21.2" }
pzzld-core = { features = [], optional = true, path = "../core", version = "0.1.0" }
pzzld-wallets = { features = [], optional = true, path = "../wallets", version = "0.1.0" }

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]
