[build]
dist = "dist"
target = "index.html"

[serve]
address = "0.0.0.0"
no_autoreload = false
open = false
port = 8080

[[hooks]]
stage = "build"
command = "bash"
command_arguments = ["-c", "echo 'Hello, world!'"]
