tasks:
  - init: |
      sudo apt upgrade -y && sudo apt update -y && sudo apt autoremove -y
      sudo apt-get install -y protobuf-compiler
      rustup default nightly
      rustup component add clippy rustfmt --toolchain nightly
      rustup target add wasm32-unknown-unknown wasm32-wasi --toolchain nightly
      cp .env.example .env
    command: cargo build --release --workspace
