version: "4"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pzzld
    depends_on: [ cache ]
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - .config:/config
      - /data:/data
  cache:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - /data/redis:/usr/local/etc/redis

volumes:
  config:
  data:
