version: "4"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pzzld
    env_file:
      - .env
    platform: wasi/wasm32
    ports:
      - "8080:8080"
    restart: always
    runtime: io.containerd.wasmedge.v1
    volumes:
      - .config:/config
      - /data:/data

volumes:
  config:
  data:
