[build]
dist = "dist"
filehash = true
public_url = "/"
release = false
target = "wasm/index.html"

[clean]
cargo = false
dist = "dist"

[serve]
address = "127.0.0.1"
no_autoreload = false
open = false
port = 8000

[tools]
sass = "1.54.9"
wasm_bindgen = "0.2.83"
wasm_opt = "version_110"

[watch]
watch = []
ignore = []

[[hooks]]
command = "sh"
command_arguments = ["-c", "cargo build --release -p pzzld"]
stage = "pre_build"
