[package]
authors.workspace = true
categories = []
default-run = "puzzled"
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords = []
license.workspace = true
name = "puzzled"
readme.workspace = true
repository.workspace = true
version.workspace = true

[[bin]]
bench = false
name = "puzzled"
test = false

[build-dependencies]

[dependencies]
pzzld = { features = [], path = "../../pzzld", version = "0.1.0" }

clap = { features = ["derive", "env"], version = "4" }
serde.workspace = true
serde_json.workspace = true
smart-default.workspace = true
strum.workspace = true
tracing = { features = ["log"], version = "0.1" }

[dev-dependencies]

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]

[target.wasm32-unknown-unknown]

[target.wasm32-wasi]
