client_id = ""
client_secret = ""
mode = "development"
name = "Puzzled"

[logger]
level = "info"

[server]
host = "127.0.0.1"
port = 8080

[services]

[services.oauth]
auth = ""
redirect = ""
token= ""
