mode = "development"

[auth]
id = ""
secret = ""
redirect = ""
token = ""

[logger]
level = "info"

[gateway]
endpoint = "https://gateway.storjshare.io"
region = "us-east-1"

[server]
host = "127.0.0.1"
port = 8080
