name: Firebase

concurrency:
  group: "firebase"
  cancel-in-progress: false

env:
  FIREBASE_PID: curiosity-2f6e1

on:
  push:
    branches: [ main ]
    tags: [ v*.*.* ]
  release:
    types: [ published ]
  repository_dispatch:
    types: [ firebase ]
  workflow_dispatch:

permissions:
  contents: read
  deployments: write
  id-token: write
  pages: write

jobs:
  publish:
    environment:
      name: production
      url: https://${{ env.FIREBASE_PID }}.web.app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: rustup
        run: |
          rustup default nightly
          rustup target add wasm32-unknown-unknown --toolchain nightly
      - name: trunkrs
        run: cargo install trunk wasm-bindgen-cli
      - name: build
        run: trunk --config pzzld/Trunk.toml build --release
      - name: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          channelId: live
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PZZLD_384500 }}'
          projectId: ${{ env.FIREBASE_PID }}
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
