name: nightly

env:
  CARGO_TERM_COLOR: always

on:
  schedule:
    - cron: "30 9 * * *"

jobs:
  rust:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Build
        run: cargo build -v
      - name: Test
        run: cargo test --all --all-features -v
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        workdir:
          - .
        image: 
          - pzzld
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker buildx build --tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image }} ${{ matrix.workdir }}
